apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-ing
  namespace: ${CICD_GIT_REPO_NAME}
  annotations:
    # 憑證產生
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod-${CICD_GIT_REPO_NAME}"
spec:
  tls:
  - hosts:
    - "web-${CICD_GIT_BRANCH}-${CICD_GIT_REPO_NAME}.120.105.129.176.xip.io"
    secretName: web-${CICD_GIT_BRANCH}-${CICD_GIT_REPO_NAME}-xip-tls
  rules:
  - host: "web-${CICD_GIT_BRANCH}-${CICD_GIT_REPO_NAME}.120.105.129.176.xip.io"
    http:
      paths:
      - backend:
          serviceName: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-svc
          servicePort: 8080
        path: "/"
        pathType: "ImplementationSpecific"
